<?php
/*
	Allow the requests to be sent outside of the current origin. This is needed because we want to send the credit card details straight to Paybyway API.
*/
Header('Access-Control-Allow-Origin', '*');
Header('Access-Control-Allow-Methods', 'POST');
Header("Access-Control-Allow-Headers", "X-Requested-With");

define("CHARGE_SUCCEEDED", 0);
define("CHARGE_FAILED", 1);

/*
	Include the PHP library
*/
include_once('rest-php-lib/lib/paybyway_loader.php');

/*
	Autoloader setup for Composer
	include_once('rest-php-lib/vendor/autoload.php');
*/

/*
	Create instance of the lib and define api_key and private_key
	Paybyway('api_key', 'private_key')
*/

$payment = new Paybyway\Paybyway('api_key', 'private_key');

/*
	Catch get_token post from the form. This call is the first one we make. 
	The token query that is then generated by the PHP library includes all the information we need to know about the order.
	API and Lib references: https://www.paybyway.com/docs/web_payments/
*/
if(isset($_GET['action']) && $_GET['action'] == 'get_token')
{
	$payment->addCharge(
		array(
		'order_number' => 'lalllaa123_' . time(), 
		'amount' => 472, 
		'currency' => 'EUR' 
		)
	);

	$payment->addCustomer(
		array(
			'firstname' => 'Teppo', 
			'lastname' => 'Testaaja', 
			'email' => 'testi@paybyway.com', 
			'address_street' => 'Testaddress 1',
			'address_city' => 'Testlandia',
			'address_zip' => '12345'
		)
	);

	$payment->addProduct(
		array(
			'id' => 'as123', 
			'title' => 'Product 1',
			'count' => 1,
			'pretax_price' => 300,
			'tax' => 24,
			'price' => 372,
			'type' => 1
		)
	);
  
	$payment->addProduct(
		array(
			'id' => 'ab1', 
			'title' => 'Shipping',
			'count' => 1,
			'pretax_price' => 100,
			'tax' => 0,
			'price' => 100,
			'type' => 2
		)
	);

	try
	{
		// Return the response of the query back to the form, assuming to get token of the created charge request
		$response = $payment->createCharge();
		echo $response->token;
	}
	catch (Paybyway\PaybywayException $e) 
	{
		// Error occured
		error_log($e->getMessage());
		header("HTTP/1.1 500 Internal Server Error", true, 500);
	}
	exit(0);
}

if(isset($_GET['action']) && $_GET['action'] == 'check')
{
	try
	{
		// Checks the Paybyway interface if there is a payment with given token created and in which state is it
		$charge_result = $payment->checkStatus($_POST['token']);
		if($charge_result->result == CHARGE_SUCCEEDED)
		{
			/* 
			Handling if the payment was successful
			for example update order status in database
			*/
		}
		else
		{
			/*
			Handling if the payment was failed
			for example update order status in database
			*/
		}

		/*
		Echo result to client so client knows whether payment was successful
		This is caught in paybyway.js and paymentOk() or paymentFail() js-functions are called accordingly
		*/
		echo $charge_result->result;
	}
	catch (Paybyway\PaybywayException $e) 
	{
		error_log($e->getMessage());
		header("HTTP/1.1 500 Internal Server Error", true, 500);
	}
	exit(0);
}

?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Maksukaista - Web payment demo</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		<link href="bootstrap/css/bootstrap.css" rel="stylesheet">
		<script type="text/javascript" src="Paybyway.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
		<style type="text/css">body{padding-top:5px;}p{padding:5px;}</style>
	</head>
	<body>
  		<div class="container-fluid">
		<div class="row">
		<div class="col-xs-12">
			<img src="images/maksukaista_pbw_white_250.png" />
			<h1>Demoshop</h1>

			<form id="the-form" action="#" role="form" autocomplete="off">
				<div class="row">
					<div class="col-xs-12">
						<div class="row">
							<div class="col-xs-12">
								<div class="form-group">
									<label for="amount">Product</label>
									<select id="amount" class="form-control">
										<option value="4.72">4,72 EUR</option>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<p class="bg-muted">Please enter your card details.</p>
							</div>
						</div>

						<div class="form-group">
							<label for="cardNumber">Card number</label>
							<input type="number" id="cardNumber" lenght="30" placeholder="Enter the card number" class="form-control"/>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6">
						<div class="form-group">
							<label for="expMonth">Month</label>
							<select id="expMonth" class="form-control card-exp-month">
								<option>01</option>
								<option>02</option>
								<option>03</option>
								<option>04</option>
								<option>05</option>
								<option>06</option>
								<option>07</option>
								<option>08</option>
								<option>09</option>
								<option>10</option>
								<option>11</option>
								<option>12</option>
							</select>
						</div>
					</div>
					<div class="col-xs-6">
						<div class="form-group">
							<label for="expYear">Year</label>
							<select id="expYear" class="form-control card-exp-year">
								<option>2015</option>
								<option>2016</option>
								<option>2017</option>
								<option>2018</option>
								<option>2019</option>
								<option>2020</option>
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6">
						<div class="form-group">
							<label for="cvv">CVV</label>
							<input type="number" id="cvv" maxlength="4" class="form-control" lenght="4" placeholder="Enter the CVV"/>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<input type="submit" class="btn" class="form-control" value="Pay"/>
						</div>
					</div>
				</div>
			</form>
			<div class="row">
				<div class="col-xs-12">
					<div id="payment-result"></div>
				</div>
			</div>
		</div>

	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		var paymentTimer = null;
		/*
		You may set custom urls for the api links by using:
		Paybyway.instance().setTokenUrl();
		Paybyway.instance().setCheckUrl();

		For example:
		Paybyway.instance().setCheckUrl(window.location.origin+window.location.pathname+"/check");
		or
		Paybyway.instance().setCheckUrl("https://www.example.com/index.php?action=check");
		*/

		$("#the-form").submit(function(e) 
		{
			e.preventDefault();
			var card = $('#cardNumber').val();
			var code = $('#cvv').val();

			/*
			Basic checks for card number and cvv
			*/
			if(!Paybyway.instance().validateCardNumber(card))
			{
				$("#payment-result").html("<p class=\"bg-danger\">Check card number.</p>");
				return;
			}

			if(!Paybyway.instance().validateCVV(code))
			{
				$("#payment-result").html("<p class=\"bg-danger\">Check CVV.</p>");
				return;
			}

			$('.btn').attr("disabled", "disabled");
			// api requires amount to be in currency/100.
			var amount = Paybyway.instance().convertToCents($('#amount').val());

			paymentTimer = setTimeout(function(){
				$('.btn').removeAttr("disabled");
				$("#payment-result").html("<p class=\"bg-danger\">Connection error.</p>");
			}, 20000);

			// Actual function call that invokes the backend token creation process
			Paybyway.instance().getToken(amount, "EUR");
			$("#payment-result").html("<p class=\"bg-info\">Processing...</p>");
		});

		/*
			Overwritten methods
		*/

		// Token creation was successful. This method is called by the lib when token creating was successful
		Paybyway.instance().tokenReady = function(token) 
		{
			// api requires amount to be in currency/100.
			var amount = Paybyway.instance().convertToCents($('#amount').val());
			var card = $('#cardNumber').val();    
			var expMonth = $('#expMonth').val();    
			var expYear = $('#expYear').val();    
			var code = $('#cvv').val();

			Paybyway.instance().charge(token, amount, "EUR", card, expMonth, expYear, code);
		}

		// Payment was successful. This method is called by the lib when payment was successful
		Paybyway.instance().paymentOk = function(token)
		{
			$('.btn').removeAttr("disabled");
			$("#payment-result").html("<p class=\"bg-success\">Payment successful!</p>");
	  		$("#the-form")[0].reset();
			clearTimeout(paymentTimer);
		} 

		// Payment failed. This method is called by the lib when something goes wrong
		Paybyway.instance().paymentFail = function(token)
		{
			$('.btn').removeAttr("disabled");
			$("#payment-result").html("<p class=\"bg-danger\">Payment failed!</p>");
			clearTimeout(paymentTimer);
		}
	});
</script>
</body>
</html>
